import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"
import type { Metadata } from "next"
import { Lexend, Source_Code_Pro } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/providers/themeProvider"

const lexend = Lexend({
	subsets: ["latin"],
	weight: ["300", "700"],
})
const sourceCode = Source_Code_Pro({
	subsets: ["latin"],
	weight: ["300", "600"],
	variable: "--font-source-code",
})

export const metadata: Metadata = {
	title: "3 Bad Robots",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider
			dynamic
			appearance={{ baseTheme: dark }}
			signInUrl="/sign-in"
			signUpUrl="/sign-up"
			signInFallbackRedirectUrl="/setup"
			signUpFallbackRedirectUrl="/"
			afterSignOutUrl="/">
			<html lang="en" suppressHydrationWarning>
				<body className={cn(lexend.className, "antialiased h-full")}>
					<ThemeProvider
						attribute={"class"}
						defaultTheme={"dark"}
						enableSystem
						storageKey="3badrobots-theme">
						{children}
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
